### ISSUE TITLE
time entry for morning and afternoon

### ISSUE THREAD

**Issue by hostingnuggets** [OTRS/TimeAccounting#21]
instead of having only one range of time entry (start/stop) it would be great to have the possibility to enter a start/stop range for the morning and the same for the afternoon

**Comment by mgruner** [comment]
Hello @hostingnuggets. Thanks for your suggestion! My colleage @carlosfrodriguez will review it. I'll close this one now as we actually don't use github issues to track feature suggestions.
Regards, Martin
